"""Add image file field to Post model

Revision ID: 196671b3ed6e
Revises: 02db7f3794d0
Create Date: 2024-05-27 15:22:21.659034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196671b3ed6e'
down_revision = '02db7f3794d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
